### ISSUE TITLE
Cannot use multiple module in single page

### ISSUE THREAD

**Issue by alcad** [mavrosxristoforos/rapid-contact#2]
Hi @mavrosxristoforos, I find a trouble when i try to use multiple modules in single page:
`uniqid()` function does not generate different id's for every module.

https://github.com/mavrosxristoforos/rapid-contact/blob/666947b16d474b60884c65e7fcdda4cea130f72d/mod_rapid_contact/mod_rapid_contact.php#L160

Can you replace `uniqid()` with `random_int()`, `random_bytes()`, or `openssl_random_pseudo_bytes()` instead?

If you cannot replace `uniqid()` can you imagine to replace with something like this?
`str_replace('.','',uniqid('',true))`
to generate an id with more entropy?

Best regards

**Comment by mavrosxristoforos** [comment]
Hi @alcad! Indeed, especially when running on Windows, `uniqid()` is not guaranteed to return a unique string. I can definitely change it to `random_int()`. However, we are currently in the middle of a large migration from SVN to Github and cannot issue releases that will be published at [mavrosxristoforos.com](https://mavrosxristoforos.com), just yet. I will change it here, and you can download the file [from the latest release on Github](https://github.com/mavrosxristoforos/rapid-contact/releases).
